// $check_csv_landmarks.cpp 3.0 milbo$ 
//
// Sanity check of landmarks generated by convert-shape-to-opencv-csv.awk
//
// To build:
//
// cl -nologo -O2 -W3 -MT -EHsc -DWIN32 check_csv_landmarks.cpp 
//    -IC:\OpenCV2.1\include\opencv C:\OpenCV2.1\lib\cv210.lib 
//    C:\OpenCV2.1\lib\cxcore210.lib C:\OpenCV2.1\lib\highgui210.lib 
//    ..\data\stasm_dll.lib 


#include <stdio.h>
#include <assert.h>
#if _MSC_VER==1200 // hack for Visual C 6.0 (standard OpenCV .h files cause compiler errors)
  #include "../stasm/stasm_cv.h"
#else
  #include "cv.h"
  #include "highgui.h"
#endif
#include "../stasm/stasm_dll.hpp"   // for AsmSearchDll

int main (void)
{
    const char *image_name = "/a1/faces/muct/bmp/i000qc-fn.bmp"; // use camera c so can check unused points

    IplImage *img = cvLoadImage(image_name, CV_LOAD_IMAGE_COLOR);
    if(img == NULL) {
        printf("Error: Cannot open %s\n", image_name);
        return -1;
    }
    // following data cut and pasted from muct76-opencv.csv (I changed ".x" to "" to convert double to int)
    int landmarks[] = 
            { 
            212,352,203,380,200,407,211,439,224,479,243,498,270,509,303,511,319,501,326,483,330,466,346,436,355,415,361,389,354,346,0,0,354,319,342,325,325,334,344,334,356,328,250,334,267,331,280,333,294,339,280,341,267,339,251,352,265,345,277,354,264,358,262,351,350,346,339,341,329,349,341,353,340,344,304,356,309,384,285,401,295,414,316,418,0,0,0,0,330,384,321,356,304,411,0,0,262,441,286,437,303,434,310,435,320,434,328,433,334,435,327,449,320,459,305,462,291,460,278,454,288,451,308,451,319,447,320,438,308,441,290,441,307,446,327,405,258,348,271,349,270,356,257,355,344,343,334,345,335,351,345,349
            };
    int nlandmarks = sizeof(landmarks) / (2 * sizeof(int));

    printf("width %d height %d nlandmarks %d\n", img->width, img->height, nlandmarks);
    fflush(stdout);

    // draw the landmarks on the image

    assert(sizeof(int) == 4); // needed for CvPoint typecast below
    int *p = landmarks;
    cvPolyLine(img, (CvPoint **)&p, &nlandmarks, 1, 1, CV_RGB(255,0,0));

    // show the image with the landmarks

    cvShowImage("stasm example", img);
    cvWaitKey(0);
    cvDestroyWindow("stasm example");
    cvReleaseImage(&img);

    return 0;
}
